### ISSUE TITLE
Php doc missing

### ISSUE THREAD

**Issue by mindaugas-laurinaitis** [adaptdk/media_skyfish#12]
https://github.com/adaptdk/media_skyfish/blob/dfcc076d26c0a774ee7ac5c4cfb4cc67c1e3ca56/src/Plugin/EntityBrowser/Widget/SkyfishWidget.php#L21

And both services are missing php doc for constants , functions. And even more is invalid - missing type, comment of parameters

**Comment by irmantasp** [comment]
Solved on #9
